import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'ko' | 'en' | 'zh';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 기본 번역 데이터
const translations = {
    ko: {
        // Navigation
        home: '홈',
        about: '회사소개',
        products: '제품소개',
        equipment: '건설기계소개',
        shop: '온라인 스토어',
        projects: '시공사례',
        certificates: '시험성적서/인증',
        qna: '고객상담',
        news: '공지사항',
        resources: '자료실',
        contact: '연락처',

        // User menu
        admin: '관리자',
        user: '사용자',
        revenue_management: '매출 관리',
        admin_danger_zone: '관리자 위험구역',
        profile_settings: '프로필 설정',
        login: '로그인',
        logout: '로그아웃',
        welcome: '환영합니다!',
        admin_account: '관리자 계정',

        // Hero Section
        hero_patent: '특허 제10-2312833호',
        hero_trademark: '상표 제40-1678504호',
        hero_title_line1: '친환경 불연재(1액형)',
        hero_title_line2: '신소재 세라믹 코팅제',
        hero_inquiry_btn: '제품 문의하기',
        hero_purchase_btn: '제품 구매하기',
        hero_projects_btn: '시공사례 보기',
        hero_admin_youtube_edit: '메인 유튜브 영상 링크 수정',
        hero_youtube_placeholder: '유튜브 영상 주소 입력',
        hero_embed_preview: '변환된 embed 주소:',
        hero_save_btn: '저장',
        hero_saving: '저장 중...',
        hero_save_success: '유튜브 링크가 저장되었습니다.',

        // Features Section
        features_title: '린코리아만의',
        features_title_highlight: '특별함',
        features_subtitle: '최고 품질의 세라믹 코팅제로 안전하고 친환경적인 건설환경을 만들어갑니다',

        // Feature items
        feature_fire_resistant_title: '불연재 인증',
        feature_fire_resistant_desc: '안전한 순수 무기질 세라믹 코팅제',
        feature_eco_friendly_title: '친환경 마감 공법',
        feature_eco_friendly_desc: '환경을 생각하는 친환경적인 1액형 신소재 세라믹 코팅마감',
        feature_quality_title: '우수한 품질',
        feature_quality_desc: '다양한 시험성적서와 인증, 1000여 곳 이상의 현장 적용을 통해 검증된 품질',
        feature_industrial_title: '산업용 적용',
        feature_industrial_desc: '다양한 건설 현장에서 검증된 신뢰성',
        feature_time_saving_title: '공기 단축',
        feature_time_saving_desc: '콘크리트 폴리싱의 단계를 획기적으로 단축시켜 간편하고 신속한 시공 가능',
        feature_verified_title: '검증된 성능',
        feature_verified_desc: '엄격한 품질 테스트를 통과한 제품',

        // Footer
        footer_company_info: '회사 정보',
        footer_address: '인천광역시 서구 백범로 707 (주안국가산업단지)',
        footer_business_number: '사업자등록번호: 747-42-00526',
        footer_quick_links: '메뉴 안내',
        footer_customer_service: '고객센터',
        footer_social_media: '소셜 미디어',
        footer_copyright: '© 2025 린코리아. All rights reserved.',

        // About Page
        about_hero_title: '회사소개',
        about_hero_subtitle: '건설재료 제조 전문 기업 린코리아는 혁신적인 기술과 품질로 건설업계의 새로운 기준을 제시합니다.',
        about_intro_title: '린코리아 소개',
        about_intro_description: '린코리아는 건설재료와 건설기계 분야에서 혁신적인 솔루션을 제공하는 전문 기업으로 성장해왔습니다. 최고의 품질과 기술력으로 고객의 성공을 위한 최적의 파트너가 되겠습니다.',
        about_vision: '비전',
        about_vision_desc: '건설업계의 혁신을 선도하는 글로벌 기업',
        about_mission: '미션',
        about_mission_desc: '최고의 품질과 기술로 고객 가치 창출',
        about_core_values: '핵심가치',
        about_core_values_desc: '신뢰, 혁신, 지속가능성',
        about_business_title: '사업 영역',
        about_business_subtitle: '린코리아는 건설재료와 건설기계 두 가지 핵심 사업을 통해 건설업계의 발전을 이끌어가고 있습니다.',
        about_materials_title: '건설재료사업부',
        about_materials_subtitle: '핵심 사업 영역',
        about_materials_desc: '콘크리트 표면마감 1액형 세라믹코팅제(불연재), 방열도료, 특수목적코팅제 등 최고 품질의 제품을 생산하는 린코리아의 핵심 사업부입니다.',
        about_equipment_title: '건설기계사업부',
        about_equipment_subtitle: 'Shanghai JS Floor Systems 공식 파트너',
        about_equipment_desc: 'Shanghai JS Floor Systems의 공식 파트너사로서 한국 공식 판매업체 및 서비스센터를 운영하고 있습니다. 세계적인 공사 현장에서 사용되는 콘크리트 연삭기 및 연마기 시장의 선두주자입니다.',
        about_location_title: '오시는 길',
        about_address_label: '주소',
        about_phone_label: '전화',
        about_email_label: '이메일',

        // Projects Page
        projects_hero_title: '시공사례',
        projects_hero_subtitle: '린코리아의 혁신적인 세라믹 코팅 기술이 적용된 다양한 프로젝트 사례를 확인해보세요.',
        projects_add_btn: '프로젝트 추가',
        projects_no_projects: '등록된 프로젝트가 없습니다.',
        projects_admin_add: '새 프로젝트 추가',
        projects_form_title_add: '프로젝트 추가',
        projects_form_title_edit: '프로젝트 수정',
        projects_form_name: '프로젝트명',
        projects_form_location: '위치',
        projects_form_description: '설명',
        projects_form_image: '이미지 URL',
        projects_form_features: '특징',
        projects_form_category: '카테고리',
        projects_form_add_feature: '새로운 특징을 입력하세요',
        projects_delete_confirm: '정말로 이 프로젝트를 삭제하시겠습니까?',
        projects_delete_title: '프로젝트 삭제',
        projects_saving: '저장 중...',
        projects_view_detail: '자세히 보기',
        projects_delete_error: '프로젝트 삭제에 실패했습니다.',
        projects_delete_success: '프로젝트가 삭제되었습니다.',

        // Products Page
        products_hero_title: '제품소개',
        products_hero_subtitle: '린코리아의 혁신적인 제품군을 만나보세요. 최고 품질과 기술력으로 안전한 건설환경을 만들어갑니다.',
        products_add_btn: '제품 추가',
        products_form_title_add: '제품 추가',
        products_form_title_edit: '제품 수정',
        products_form_name: '제품명',
        products_form_description: '설명',
        products_form_image: '이미지 URL',
        products_form_features: '특징',
        products_form_price: '가격',
        products_form_category: '카테고리',
        products_form_add_feature: '새로운 특징을 입력하세요',
        products_delete_confirm: '정말로 이 제품을 삭제하시겠습니까?',
        products_delete_title: '제품 삭제',
        products_saving: '저장 중...',
        products_save_success: '제품이 수정되었습니다.',
        products_add_success: '제품이 추가되었습니다.',
        products_error_occurred: '오류가 발생했습니다.',
        products_view_detail: '자세히 보기',

        // Equipment Page
        equipment_hero_title: '건설기계소개',
        equipment_hero_subtitle: '최첨단 기술의 콘크리트 연삭기로 최고의 품질과 효율성을 제공합니다.',
        equipment_add_btn: '기계 추가',
        equipment_partnership_title: 'Shanghai JS Floor Systems 공식 파트너',
        equipment_partnership_desc: 'Shanghai JS Floor Systems의 공식 파트너사로서 한국 공식 판매업체 및 서비스센터를 운영하고 있습니다. 세계적인 공사 현장에서 사용되는 콘크리트 연삭기 시장의 선두주자입니다.',
        equipment_partnership_contact: '한국 공식판매 & 공식서비스센터(AS)\n주소: 인천\n문의전화: 032-571-1023',
        equipment_construction_tab: '건설기계',
        equipment_diatool_tab: '다이아툴',
        equipment_premium_title: '최신형 콘크리트 연삭기',
        equipment_premium_subtitle: '최첨단 기술이 적용된 프리미엄 연삭기 라인업',
        equipment_professional_title: '콘크리트 연삭기',
        equipment_professional_subtitle: '전문가를 위한 고성능 연삭기 시리즈',
        equipment_diatool_title: '다이아툴',
        equipment_diatool_subtitle: '고품질 다이아몬드 공구 및 액세서리',
        equipment_diatool_empty: '다이아툴 제품이 준비 중입니다.',
        equipment_diatool_add: '다이아툴 추가',
        equipment_features_label: '주요 특징:',
        equipment_edit_modal_title: '기계 수정',
        equipment_add_modal_title: '기계 추가',
        equipment_delete_modal_title: '기계 삭제',
        equipment_delete_confirm: '정말로 기계를 삭제하시겠습니까?',
        equipment_form_name: '이름',
        equipment_form_description: '설명',
        equipment_form_image: '이미지 URL',
        equipment_form_icon: '아이콘',
        equipment_form_category: '카테고리',
        equipment_form_features: '특징',
        equipment_form_add_feature: '새로운 특징을 입력하세요',
        equipment_saving: '저장 중...',

        // Common
        loading: '로딩 중...',
        error: '오류',
        success: '성공',
        cancel: '취소',
        confirm: '확인',
        save: '저장',
        edit: '편집',
        delete: '삭제',
        add: '추가',
        search: '검색',
        filter: '필터',
        reset: '재설정',

        // Language names
        korean: '한국어',
        english: 'English',
        chinese: '中文',

        // QnA Page
        qna_hero_title: '고객상담',
        qna_hero_subtitle: '궁금한 것이 있으시면 언제든지 문의해 주세요. 전문가가 신속하고 정확하게 답변드립니다.',
        qna_search_placeholder: '검색어를 입력하세요',
        qna_filter_all: '전체',
        qna_filter_public: '공개',
        qna_filter_private: '비공개',
        qna_filter_answered: '답변완료',
        qna_filter_unanswered: '답변대기',
        qna_ask_question: '질문하기',
        qna_no_questions: '등록된 질문이 없습니다.',
        qna_form_title_add: '질문 작성',
        qna_form_title_edit: '질문 수정',
        qna_form_category: '카테고리',
        qna_form_title: '제목',
        qna_form_content: '내용',
        qna_form_is_private: '비공개 질문',
        qna_form_is_private_desc: '체크하시면 관리자와 작성자만 볼 수 있습니다.',
        qna_category_general: '일반 문의',
        qna_category_product: '제품 문의',
        qna_category_order: '주문/배송',
        qna_category_technical: '기술 지원',
        qna_category_other: '기타',
        qna_status_answered: '답변완료',
        qna_status_pending: '답변대기',
        qna_private_question: '비공개 질문',
        qna_public_question: '공개 질문',
        qna_delete_confirm: '정말로 이 질문을 삭제하시겠습니까?',
        qna_delete_title: '질문 삭제',
        qna_answer_placeholder: '답변을 입력하세요...',
        qna_submit_answer: '답변 등록',
        qna_edit_answer: '답변 수정',
        qna_delete_answer: '답변 삭제',
        qna_answer_delete_confirm: '정말로 이 답변을 삭제하시겠습니까?',

        // QnA Additional
        total_inquiries: '전체 문의',
        no_search_results: '검색 결과가 없습니다',
        try_different_search: '다른 검색어나 필터를 시도해보세요',
        leave_first_inquiry: '첫 번째 문의를 남겨주세요',
        login_to_inquire: '로그인하여 문의하기',

        // News Page
        news_hero_title: '공지사항',
        news_hero_subtitle: '린코리아의 최신 소식과 중요한 공지사항을 확인하세요.',
        news_add_btn: '공지 추가',
        news_no_news: '등록된 공지사항이 없습니다.',
        news_form_title_add: '공지 추가',
        news_form_title_edit: '공지 수정',
        news_form_title: '제목',
        news_form_content: '내용',
        news_form_image: '이미지 URL',
        news_form_category: '카테고리',
        news_form_is_important: '중요 공지',
        news_form_is_important_desc: '체크하시면 상단에 고정 표시됩니다.',
        news_delete_confirm: '정말로 이 공지를 삭제하시겠습니까?',
        news_delete_title: '공지 삭제',
        news_category_announcement: '일반 공지',
        news_category_event: '이벤트',
        news_category_update: '업데이트',
        news_category_maintenance: '점검',
        news_view_detail: '자세히 보기',
        news_important: '중요',
        news_date_format: 'MM/DD/YYYY',
        publish_immediately: 'Publish Immediately',

        // Contact Page
        contact_hero_title: '연락처',
        contact_hero_subtitle: '린코리아에 문의하실 사항이 있으시면 언제든지 연락해 주세요.',
        contact_company_info: '회사 정보',
        contact_address: '주소',
        contact_phone: '전화번호',
        contact_fax: '팩스',
        contact_email: '이메일',
        contact_business_hours: '영업시간',
        contact_business_hours_detail: '평일 09:00 - 18:00 (토/일/공휴일 휴무)',
        contact_map_title: '오시는 길',
        contact_form_title: '문의하기',
        contact_form_name: '이름',
        contact_form_email: '이메일',
        contact_form_phone: '전화번호',
        contact_form_subject: '제목',
        contact_form_message: '메시지',
        contact_form_send: '메시지 보내기',
        contact_form_required: '필수 항목',
        contact_send_success: '메시지가 성공적으로 전송되었습니다.',
        contact_send_error: '메시지 전송에 실패했습니다.',

        // Resources Page
        resources_hero_title: '자료실',
        resources_hero_subtitle: '린코리아의 제품 카탈로그, 기술 자료, 인증서 등 다양한 자료를 확인하세요.',
        resources_add_btn: '자료 추가',
        resources_no_resources: '등록된 자료가 없습니다.',
        resources_form_title_add: '자료 추가',
        resources_form_title_edit: '자료 수정',
        resources_form_title: '제목',
        resources_form_description: '설명',
        resources_form_file_url: '파일 URL',
        resources_form_file_type: '파일 형식',
        resources_form_category: '카테고리',
        resources_delete_confirm: '정말로 이 자료를 삭제하시겠습니까?',
        resources_delete_title: '자료 삭제',
        resources_category_catalog: '제품 카탈로그',
        resources_category_technical: '기술 자료',
        resources_category_certificate: '인증서',
        resources_category_manual: '사용 설명서',
        resources_category_other: '기타',
        resources_download: '다운로드',
        resources_file_type_pdf: 'PDF',
        resources_file_type_doc: 'DOC',
        resources_file_type_image: '이미지',
        resources_file_type_other: '기타',
        search_resources: '자료 검색...',
        all_categories: '전체 카테고리',
        download_count: '다운로드',
        hide: '숨기기',
        show: '보이기',
        grid_view: '격자',
        list_view: '목록',
        total_resources_count: '총 {{count}}개의 자료가 있습니다',
        search_results_for: "'{{term}' 검색 결과",
        no_resources_found: '자료가 없습니다',
        try_different_filter: '검색 조건을 변경하거나 다른 카테고리를 확인해보세요.',
        hidden: '숨김',
        download_count_suffix: '회',
        downloading: '다운로드 중...',
        processing: '처리중...',

        // Shop Page
        shop_hero_title: '온라인 쇼핑몰',
        shop_hero_subtitle: '린코리아 제품을 온라인으로 주문하고 구매할 수 있습니다.',
        shop_add_product: '제품 추가',
        shop_delete_title: '제품 삭제',
        shop_sort_select: '정렬 방식 선택',
        shop_sort_newest: '최신등록순',
        shop_sort_price_low: '낮은 가격순',
        shop_sort_price_high: '높은 가격순',
        shop_grid_label: '그리드',
        shop_grid_setting: '그리드 설정',
        shop_grid_apply: '적용',
        shop_grid_applying: '적용 중...',
        shop_product_out_of_stock: '품절',
        shop_product_buy_now: '구매하기',
        shop_deleted_success: '삭제되었습니다.',
        reviews: '리뷰',
        currency_won: '원',

        // Shop Additional
        shop_sort_popularity: '인기도순',
        shop_sort_discount: '할인율순',
        shop_sort_sales: '누적 판매순',
        shop_sort_rating: '평점 높은순',

        // Product Benefits
        product_benefits_title: '제품의 장점',
        product_benefits_subtitle: '린코리아 세라믹 코팅제가 선택받는 이유',
        product_benefits_fire_resistant_title: '불연재 인증',
        product_benefits_fire_resistant_desc: '안전한 순수 무기질 세라믹 코팅제',
        product_benefits_easy_construction_title: '간편한 시공',
        product_benefits_easy_construction_desc: '1액형으로 간편하게 시공 가능',
        product_benefits_quality_title: '우수한 품질',
        product_benefits_quality_desc: '엄격한 품질 관리를 통한 우수한 품질',
        product_benefits_variety_title: '다양한 선택',
        product_benefits_variety_desc: '용도와 요구사항에 맞는 다양한 제품군',

        // Equipment Success Messages
        equipment_updated_success: '기계가 수정되었습니다.',
        equipment_added_success: '기계가 추가되었습니다.',

        // Revenue Management
        revenue_management_title: '매출 관리',
        revenue_management_subtitle: '데이터 기반의 매출 분석과 시각화로 비즈니스 인사이트를 얻어보세요',
        revenue_dashboard: '대시보드',
        revenue_chart_analysis: '차트 분석',
        revenue_data_input: '데이터 입력',
        revenue_data_manage: '데이터 편집',
        revenue_quick_select: '빠른 선택',
        revenue_period: '기간',
        revenue_export_data: '데이터 내보내기',
        revenue_monthly_trend: '월별 매출 추이',
        revenue_data_loading_error: '데이터 로딩 오류',
        revenue_no_data: '매출 데이터가 없습니다',
        revenue_no_data_desc: '데이터 입력 탭에서 매출 정보를 추가하여 분석을 시작해보세요.',
        revenue_input_data: '데이터 입력하기',

        // Revenue Table Headers
        revenue_date: '날짜',
        revenue_category: '카테고리',
        revenue_product_name: '제품명',
        revenue_amount: '매출',
        revenue_quantity: '수량',
        revenue_unit_price: '단가',
        revenue_region: '지역',
        revenue_customer_type: '고객유형',
        revenue_notes: '비고',

        // ProductCard
        product_card_view_detail: '자세히 보기',
        product_card_show: '표시하기',
        product_card_hide: '숨기기',
        product_card_edit: '편집',
        product_card_delete: '삭제',

        // Certificates Page
        certificates_hero_title: '시험성적서/인증',
        certificates_hero_subtitle: '린코리아 제품의 우수한 품질과 안전성을 증명하는 각종 인증서와 시험성적서를 확인하세요.',
        certificates_add_btn: '인증서 추가',
        certificates_no_certificates: '등록된 인증서가 없습니다.',
        certificates_patent_trademark_title: '특허 및 상표 등록증',
        certificates_patent_trademark_desc: '린코리아의 기술력과 브랜드를 보증하는 공식 문서들',
        certificates_rincoat_test_title: 'RIN-COAT 시험성적서',
        certificates_rincoat_test_desc: '공인시험기관에서 실시한 품질 시험 결과 전체 문서',
        certificates_rin_test_title: '린코리아 시험성적서',
        certificates_rin_test_desc: '린코리아 제품의 품질을 검증하는 시험성적서',
        certificates_type_patent: '특허 등록증',
        certificates_type_patent_desc: '1액형 세라믹 제조기술에 대한 특허 등록으로 기술력을 인정받았습니다.',
        certificates_type_fireproof: '불연재 인증',
        certificates_type_fireproof_desc: '안전한 순수 무기질 세라믹 코팅제입니다',
        certificates_type_quality: '품질시험성적서',
        certificates_type_quality_desc: '공인시험기관에서 실시한 각종 품질 시험 결과를 확인할 수 있습니다.',
        certificates_form_title_add: '인증서 추가',
        certificates_form_title_edit: '인증서 수정',
        certificates_form_name: '인증서명',
        certificates_form_description: '설명',
        certificates_form_image_url: '이미지 URL',
        certificates_form_category: '카테고리',
        certificates_form_issue_date: '발급일',
        certificates_form_expiry_date: '만료일',
        certificates_delete_confirm: '정말로 이 인증서를 삭제하시겠습니까?',
        certificates_delete_title: '인증서 삭제',
        certificates_updated: '인증서가 수정되었습니다.',
        certificates_added: '인증서가 추가되었습니다.',

        // QnA Form & Item Additional
        required_fields: '제목과 내용을 입력해주세요.',
        submit_error: '문의 등록에 실패했습니다.',
        anonymous: '익명',
        hide_content: '내용 숨기기',
        show_content: '내용 보기',
        private_inquiry: 'This is a private inquiry',

        // Profile Page
        profile_settings: '프로필 설정',
        profile_subtitle: '회원정보를 확인하고 수정할 수 있습니다.',
        profile_name: '이름',
        profile_email: '이메일',
        profile_company: '회사명',
        profile_phone: '연락처',
        profile_phone_error: '전화번호 형식이 올바르지 않습니다. 예: 010-1234-5678',
        profile_password_change: '비밀번호 변경',
        profile_current_password: '현재 비밀번호',
        profile_new_password: '새 비밀번호',
        profile_confirm_password: '새 비밀번호 확인',
        profile_password_warning: '비밀번호를 잊어버리면 복구할 수 없으니 안전한 곳에 보관해주세요.',
        profile_save: '저장',
        profile_saving: '저장 중...',
        profile_account_delete: '계정 탈퇴',
        profile_account_delete_warning: '계정을 탈퇴하면 모든 데이터가 영구적으로 삭제되며 복구할 수 없습니다.',
        profile_account_delete_confirm_title: '계정 탈퇴 확인',
        profile_account_delete_confirm_message: '정말로 계정을 탈퇴하시겠습니까? 이 작업은 되돌릴 수 없으며, 모든 데이터가 영구적으로 삭제됩니다.',
        profile_update_success: '프로필이 성공적으로 저장되었습니다.',
        profile_update_failed: '프로필 업데이트 실패',
        profile_password_all_required: '모든 항목을 입력해주세요.',
        profile_password_mismatch: '새 비밀번호가 일치하지 않습니다.',
        profile_password_min_length: '비밀번호는 8자 이상이어야 합니다.',
        profile_password_current_invalid: '현재 비밀번호가 올바르지 않습니다.',
        profile_password_change_failed: '비밀번호 변경에 실패했습니다. 다시 시도해주세요.',
        profile_password_change_success: '비밀번호가 성공적으로 변경되었습니다.',
        profile_delete_success: '계정이 성공적으로 삭제되었습니다.',
        profile_delete_failed: '계정 탈퇴 실패',
        loading: '로딩 중...',
        saving: '저장 중...',
        saved_success: '저장되었습니다.',

        // Company Overview Section
        company_overview_title_reliable: '신뢰할 수 있는',
        company_overview_title_partner: '파트너',
        company_overview_description: '린코리아는 건설재료사업부와 2024년 신설된 건설기계사업부를 통해 종합적인 건설 솔루션을 제공합니다.',
        company_overview_location_label: '본사 위치',
        company_overview_location_value: '인천광역시 서구 백범로 707 (주안국가산업단지)\n천안 테크노파크 산업단지 입주예정 (2026~)',
        company_overview_business_number_label: '사업자등록번호',
        company_overview_business_number_value: '747-42-00526',
        company_overview_business_division_label: '사업부문',
        company_overview_business_division_value: '건설재료사업부 / 건설기계사업부',
        company_overview_learn_more: '회사소개 자세히 보기',
        company_overview_contact: '연락하기',
    },
    en: {
        // Navigation
        home: 'Home',
        about: 'About Us',
        products: 'Products',
        equipment: 'Equipment',
        shop: 'Online Store',
        projects: 'Projects',
        certificates: 'Certificates',
        qna: 'Q&A',
        news: 'News',
        resources: 'Resources',
        contact: 'Contact',

        // User menu
        admin: 'Admin',
        user: 'User',
        revenue_management: 'Revenue Management',
        admin_danger_zone: 'Admin Danger Zone',
        profile_settings: 'Profile Settings',
        login: 'Login',
        logout: 'Logout',
        welcome: 'Welcome!',
        admin_account: 'Admin Account',

        // Hero Section
        hero_patent: 'Patent No. 10-2312833',
        hero_trademark: 'Trademark No. 40-1678504',
        hero_title_line1: 'Eco-friendly Fire-resistant',
        hero_title_line2: 'New Ceramic Coating Material',
        hero_inquiry_btn: 'Product Inquiry',
        hero_purchase_btn: 'Purchase Products',
        hero_projects_btn: 'View Projects',
        hero_admin_youtube_edit: 'Edit Main YouTube Video Link',
        hero_youtube_placeholder: 'Enter YouTube video URL',
        hero_embed_preview: 'Converted embed URL:',
        hero_save_btn: 'Save',
        hero_saving: 'Saving...',
        hero_save_success: 'YouTube link has been saved.',

        // Features Section
        features_title: 'What Makes',
        features_title_highlight: 'RIN Korea Special',
        features_subtitle: 'Creating a safe and eco-friendly construction environment with the highest quality ceramic coating materials',

        // Feature items
        feature_fire_resistant_title: 'Fire-resistant Certification',
        feature_fire_resistant_desc: 'Safe pure inorganic ceramic coating material',
        feature_eco_friendly_title: 'Eco-friendly Finishing Method',
        feature_eco_friendly_desc: 'Environmentally friendly one-component new ceramic coating finish',
        feature_quality_title: 'Excellent Quality',
        feature_quality_desc: 'Quality verified through various test reports and certifications, applied in over 1,000 sites',
        feature_industrial_title: 'Industrial Application',
        feature_industrial_desc: 'Reliability proven in various construction sites',
        feature_time_saving_title: 'Time Saving',
        feature_time_saving_desc: 'Dramatically shortens concrete polishing steps for simple and rapid construction',
        feature_verified_title: 'Verified Performance',
        feature_verified_desc: 'Products that have passed rigorous quality testing',

        // Footer
        footer_company_info: 'Company Information',
        footer_address: 'Incheon, Seo-gu, Baekbeom-ro 707 (Juan National Industrial Complex)',
        footer_business_number: 'Business Registration Number: 747-42-00526',
        footer_quick_links: 'Quick Links',
        footer_customer_service: 'Customer Service',
        footer_social_media: 'Social Media',
        footer_copyright: '© 2025 RIN Korea. All rights reserved.',

        // About Page
        about_hero_title: 'About Us',
        about_hero_subtitle: 'RIN Korea, a specialized construction materials manufacturing company, sets new standards in the construction industry with innovative technology and quality.',
        about_intro_title: 'RIN Korea Introduction',
        about_intro_description: 'RIN Korea has grown as a specialized company providing innovative solutions in the fields of construction materials and construction machinery. We will be the optimal partner for our customers\' success with the highest quality and technology.',
        about_vision: 'Vision',
        about_vision_desc: 'A global company leading innovation in the construction industry',
        about_mission: 'Mission',
        about_mission_desc: 'Creating customer value with the highest quality and technology',
        about_core_values: 'Core Values',
        about_core_values_desc: 'Trust, Innovation, Sustainability',
        about_business_title: 'Business Areas',
        about_business_subtitle: 'RIN Korea is leading the development of the construction industry through two core businesses: construction materials and construction machinery.',
        about_materials_title: 'Construction Materials Division',
        about_materials_subtitle: 'Core Business Area',
        about_materials_desc: 'This is RIN Korea\'s core business division that produces the highest quality products such as concrete surface finishing one-component ceramic coatings (fire-resistant materials), heat-resistant paints, and special-purpose coatings.',
        about_equipment_title: 'Construction Equipment Division',
        about_equipment_subtitle: 'Shanghai JS Floor Systems Official Partner',
        about_equipment_desc: 'As an official partner of Shanghai JS Floor Systems, we operate the official sales agency and service center in Korea. We are leaders in the concrete grinder and polisher market used at construction sites worldwide.',
        about_location_title: 'Location',
        about_address_label: 'Address',
        about_phone_label: 'Phone',
        about_email_label: 'Email',

        // Projects Page
        projects_hero_title: 'Projects',
        projects_hero_subtitle: 'Discover various project cases where RIN Korea\'s innovative ceramic coating technology has been applied.',
        projects_add_btn: 'Add Project',
        projects_no_projects: 'No registered projects.',
        projects_admin_add: 'Add New Project',
        projects_form_title_add: 'Add Project',
        projects_form_title_edit: 'Edit Project',
        projects_form_name: 'Project Name',
        projects_form_location: 'Location',
        projects_form_description: 'Description',
        projects_form_image: 'Image URL',
        projects_form_features: 'Features',
        projects_form_category: 'Category',
        projects_form_add_feature: 'Enter a new feature',
        projects_delete_confirm: 'Are you sure you want to delete this project?',
        projects_delete_title: 'Delete Project',
        projects_saving: 'Saving...',
        projects_view_detail: 'View Details',

        // Additional project translations
        projects_various_title: 'Various Projects',
        projects_various_desc: 'RIN Korea Project Cases',
        projects_delete_error: 'Failed to delete project.',
        projects_delete_success: 'Project has been deleted.',

        // Equipment Page
        equipment_hero_title: 'Equipment Introduction',
        equipment_hero_subtitle: 'Providing the highest quality and efficiency with state-of-the-art concrete grinding technology.',
        equipment_add_btn: 'Add Equipment',
        equipment_partnership_title: 'Shanghai JS Floor Systems Official Partner',
        equipment_partnership_desc: 'As an official partner of Shanghai JS Floor Systems, we operate the official sales agency and service center in Korea. We are leaders in the concrete grinder market used at world-class construction sites.',
        equipment_partnership_contact: 'Korea Official Sales & Official Service Center (AS)\nAddress: Incheon\nInquiry Phone: 032-571-1023',
        equipment_construction_tab: 'Construction Equipment',
        equipment_diatool_tab: 'Diamond Tools',
        equipment_premium_title: 'Latest Concrete Grinders',
        equipment_premium_subtitle: 'Premium grinder lineup with cutting-edge technology',
        equipment_professional_title: 'Concrete Grinders',
        equipment_professional_subtitle: 'High-performance grinder series for professionals',
        equipment_diatool_title: 'Diamond Tools',
        equipment_diatool_subtitle: 'High-quality diamond tools and accessories',
        equipment_diatool_empty: 'Diamond tool products are coming soon.',
        equipment_diatool_add: 'Add Diamond Tool',
        equipment_features_label: 'Key Features:',
        equipment_edit_modal_title: 'Edit Equipment',
        equipment_add_modal_title: 'Add Equipment',
        equipment_delete_modal_title: 'Delete Equipment',
        equipment_delete_confirm: 'Are you sure you want to delete this equipment?',
        equipment_form_name: 'Name',
        equipment_form_description: 'Description',
        equipment_form_image: 'Image URL',
        equipment_form_icon: 'Icon',
        equipment_form_category: 'Category',
        equipment_form_features: 'Features',
        equipment_form_add_feature: 'Enter a new feature',
        equipment_saving: 'Saving...',

        // Common
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        cancel: 'Cancel',
        confirm: 'Confirm',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        add: 'Add',
        search: 'Search',
        filter: 'Filter',
        reset: 'Reset',
        select: 'Please select',
        none: 'None',

        // Language names
        korean: '한국어',
        english: 'English',
        chinese: '中文',

        // QnA Page
        qna_hero_title: 'Q&A',
        qna_hero_subtitle: 'If you have any questions, please feel free to contact us anytime. Our experts will respond quickly and accurately.',
        qna_search_placeholder: 'Enter search term',
        qna_filter_all: 'All',
        qna_filter_public: 'Public',
        qna_filter_private: 'Private',
        qna_filter_answered: 'Answered',
        qna_filter_unanswered: 'Pending',
        qna_ask_question: 'Ask Question',
        qna_no_questions: 'No questions registered.',
        qna_form_title_add: 'Write Question',
        qna_form_title_edit: 'Edit Question',
        qna_form_category: 'Category',
        qna_form_title: 'Title',
        qna_form_content: 'Content',
        qna_form_is_private: 'Private Question',
        qna_form_is_private_desc: 'If checked, only admin and author can see this question.',
        qna_category_general: 'General Inquiry',
        qna_category_product: 'Product Inquiry',
        qna_category_order: 'Order/Shipping',
        qna_category_technical: 'Technical Support',
        qna_category_other: 'Other',
        qna_status_answered: 'Answered',
        qna_status_pending: 'Pending',
        qna_private_question: 'Private Question',
        qna_public_question: 'Public Question',
        qna_delete_confirm: 'Are you sure you want to delete this question?',
        qna_delete_title: 'Delete Question',
        qna_answer_placeholder: 'Enter your answer...',
        qna_submit_answer: 'Submit Answer',
        qna_edit_answer: 'Edit Answer',
        qna_delete_answer: 'Delete Answer',
        qna_answer_delete_confirm: 'Are you sure you want to delete this answer?',

        // QnA Additional
        total_inquiries: 'Total Inquiries',
        no_search_results: 'No search results found',
        try_different_search: 'Try different keywords or filters',
        leave_first_inquiry: 'Leave your first inquiry',
        login_to_inquire: 'Login to Inquire',

        // News Page
        news_hero_title: 'News',
        news_hero_subtitle: 'Check out the latest news and important announcements from RIN Korea.',
        news_add_btn: 'Add Announcement',
        news_no_news: 'No announcements registered.',
        news_form_title_add: 'Add Announcement',
        news_form_title_edit: 'Edit Announcement',
        news_form_title: 'Title',
        news_form_content: 'Content',
        news_form_image: 'Image URL',
        news_form_category: 'Category',
        news_form_is_important: 'Important Announcement',
        news_form_is_important_desc: 'If checked, it will be fixed at the top.',
        news_delete_confirm: 'Are you sure you want to delete this announcement?',
        news_delete_title: 'Delete Announcement',
        news_category_announcement: 'General Announcement',
        news_category_event: 'Event',
        news_category_update: 'Update',
        news_category_maintenance: 'Inspection',
        news_view_detail: 'View Details',
        news_important: 'Important',
        news_date_format: 'MM/DD/YYYY',
        publish_immediately: 'Publish Immediately',

        // Contact Page
        contact_hero_title: 'Contact',
        contact_hero_subtitle: 'If you have any inquiries for RIN Korea, please contact us anytime.',
        contact_company_info: 'Company Information',
        contact_address: 'Address',
        contact_phone: 'Phone',
        contact_fax: 'Fax',
        contact_email: 'Email',
        contact_business_hours: 'Business Hours',
        contact_business_hours_detail: 'Weekdays 09:00 - 18:00 (Closed on Sat/Sun/Holidays)',
        contact_map_title: 'Location',
        contact_form_title: 'Contact Us',
        contact_form_name: 'Name',
        contact_form_email: 'Email',
        contact_form_phone: 'Phone',
        contact_form_subject: 'Subject',
        contact_form_message: 'Message',
        contact_form_send: 'Send Message',
        contact_form_required: 'Required Field',
        contact_send_success: 'Message has been sent successfully.',
        contact_send_error: 'Message has not been sent.',

        // Resources Page
        resources_hero_title: 'Resources',
        resources_hero_subtitle: 'Check out various materials including RIN Korea product catalogs, technical documents, certificates, and more.',
        resources_add_btn: 'Add Resource',
        resources_no_resources: 'No resources registered.',
        resources_form_title_add: 'Add Resource',
        resources_form_title_edit: 'Edit Resource',
        resources_form_title: 'Title',
        resources_form_description: 'Description',
        resources_form_file_url: 'File URL',
        resources_form_file_type: 'File Type',
        resources_form_category: 'Category',
        resources_delete_confirm: 'Are you sure you want to delete this resource?',
        resources_delete_title: 'Delete Resource',
        resources_category_catalog: 'Product Catalog',
        resources_category_technical: 'Technical Document',
        resources_category_certificate: 'Certificate',
        resources_category_manual: 'User Manual',
        resources_category_other: 'Other',
        resources_download: 'Download',
        resources_file_type_pdf: 'PDF',
        resources_file_type_doc: 'DOC',
        resources_file_type_image: 'Image',
        resources_file_type_other: 'Other',
        search_resources: 'Search resources...',
        all_categories: 'All Categories',
        download_count: 'Downloads',
        hide: 'Hide',
        show: 'Show',
        grid_view: 'Grid View',
        list_view: 'List View',
        total_resources_count: 'Total {{count}} resources found',
        search_results_for: "'{{term}}' Search Results",
        no_resources_found: 'No resources found',
        try_different_filter: 'Try different filters or explore different categories',
        hidden: 'Hidden',
        download_count_suffix: 'times',
        downloading: 'Downloading...',
        processing: 'Processing...',

        // Shop Page
        shop_hero_title: 'Online Store',
        shop_hero_subtitle: 'You can order and purchase RIN Korea products online.',
        shop_add_product: 'Add Product',
        shop_delete_title: 'Delete Product',
        shop_sort_select: 'Sort by',
        shop_sort_newest: 'Newest First',
        shop_sort_price_low: 'Lowest Price First',
        shop_sort_price_high: 'Highest Price First',
        shop_grid_label: 'Grid',
        shop_grid_setting: 'Grid Settings',
        shop_grid_apply: 'Apply',
        shop_grid_applying: 'Applying...',
        shop_product_out_of_stock: 'Out of Stock',
        shop_product_buy_now: 'Buy Now',
        shop_deleted_success: 'Deleted successfully.',
        reviews: 'Reviews',
        currency_won: 'Won',

        // Shop Additional
        shop_sort_popularity: 'Popularity',
        shop_sort_discount: 'Discount',
        shop_sort_sales: 'Sales',
        shop_sort_rating: 'Rating',

        // Product Benefits
        product_benefits_title: 'Product Benefits',
        product_benefits_subtitle: 'Why RIN Korea Ceramic Coating is Chosen',
        product_benefits_fire_resistant_title: 'Fire-resistant Certification',
        product_benefits_fire_resistant_desc: 'Safe pure inorganic ceramic coating material',
        product_benefits_easy_construction_title: 'Easy Construction',
        product_benefits_easy_construction_desc: 'Easy construction with one-component',
        product_benefits_quality_title: 'Excellent Quality',
        product_benefits_quality_desc: 'Excellent quality through strict quality management',
        product_benefits_variety_title: 'Diverse Selection',
        product_benefits_variety_desc: 'Diverse product line for various uses and requirements',

        // Equipment Success Messages
        equipment_updated_success: 'Equipment has been updated.',
        equipment_added_success: 'Equipment has been added.',

        // Certificates Page
        certificates_hero_title: 'Certificates',
        certificates_hero_subtitle: 'Check out various certificates and test reports to verify RIN Korea\'s high quality and safety.',
        certificates_add_btn: 'Add Certificate',
        certificates_no_certificates: 'No certificates registered.',
        certificates_patent_trademark_title: 'Patent and Trademark Registration',
        certificates_patent_trademark_desc: 'Official documents confirming RIN Korea\'s technology and brand',
        certificates_rincoat_test_title: 'RIN-COAT Test Report',
        certificates_rincoat_test_desc: 'Complete test report results from authorized testing agencies',
        certificates_rin_test_title: 'RIN Korea Test Report',
        certificates_rin_test_desc: 'Test report verifying the quality of RIN Korea products',
        certificates_type_patent: 'Patent Registration',
        certificates_type_patent_desc: 'Patent registration for 1-component ceramic manufacturing technology',
        certificates_type_fireproof: 'Fire-resistant Certification',
        certificates_type_fireproof_desc: 'Safe pure inorganic ceramic coating material',
        certificates_type_quality: 'Quality Test Report',
        certificates_type_quality_desc: 'You can check various quality test results from authorized testing agencies',
        certificates_form_title_add: 'Add Certificate',
        certificates_form_title_edit: 'Edit Certificate',
        certificates_form_name: 'Certificate Name',
        certificates_form_description: 'Description',
        certificates_form_image_url: 'Image URL',
        certificates_form_category: 'Category',
        certificates_form_issue_date: 'Issue Date',
        certificates_form_expiry_date: 'Expiry Date',
        certificates_delete_confirm: 'Are you sure you want to delete this certificate?',
        certificates_delete_title: 'Delete Certificate',
        certificates_updated: 'Certificate has been updated.',
        certificates_added: 'Certificate has been added.',

        // QnA Form & Item Additional
        required_fields: 'Please enter title and content.',
        submit_error: 'Failed to submit inquiry.',
        anonymous: 'Anonymous',
        hide_content: 'Hide Content',
        show_content: 'Show Content',
        private_inquiry: 'This is a private inquiry',

        // Revenue Management
        revenue_management_title: 'Revenue Management',
        revenue_management_subtitle: 'Data-driven revenue analysis and visualization to gain business insights',
        revenue_dashboard: 'Dashboard',
        revenue_chart_analysis: 'Chart Analysis',
        revenue_data_input: 'Data Input',
        revenue_data_manage: 'Data Management',
        revenue_quick_select: 'Quick Select',
        revenue_period: 'Period',
        revenue_export_data: 'Export Data',
        revenue_monthly_trend: 'Monthly Trend',
        revenue_data_loading_error: 'Data Loading Error',
        revenue_no_data: 'No revenue data',
        revenue_no_data_desc: 'Please add revenue information to start analyzing.',
        revenue_input_data: 'Input Data',

        // Revenue Table Headers
        revenue_date: 'Date',
        revenue_category: 'Category',
        revenue_product_name: 'Product Name',
        revenue_amount: 'Revenue',
        revenue_quantity: 'Quantity',
        revenue_unit_price: 'Unit Price',
        revenue_region: 'Region',
        revenue_customer_type: 'Customer Type',
        revenue_notes: 'Notes',

        // ProductCard
        product_card_view_detail: 'View Details',
        product_card_show: 'Show',
        product_card_hide: 'Hide',
        product_card_edit: 'Edit',
        product_card_delete: 'Delete',

        // Profile Page
        profile_settings: 'Profile Settings',
        profile_subtitle: 'You can view and edit your profile information here.',
        profile_name: 'Name',
        profile_email: 'Email',
        profile_company: 'Company Name',
        profile_phone: 'Phone Number',
        profile_phone_error: 'Invalid phone format. Please use the format: 010-1234-5678',
        profile_password_change: 'Change Password',
        profile_current_password: 'Current Password',
        profile_new_password: 'New Password',
        profile_confirm_password: 'Confirm New Password',
        profile_password_warning: 'If you forget your password, you won\'t be able to recover it. Please keep it safe.',
        profile_save: 'Save',
        profile_saving: 'Saving...',
        profile_account_delete: 'Delete Account',
        profile_account_delete_warning: 'Once you delete your account, all data will be permanently deleted and cannot be recovered.',
        profile_account_delete_confirm_title: 'Confirm Account Deletion',
        profile_account_delete_confirm_message: 'Are you sure you want to delete your account? This action cannot be undone and all data will be permanently deleted.',
        profile_update_success: 'Profile has been saved successfully.',
        profile_update_failed: 'Failed to update profile',
        profile_password_all_required: 'All fields are required.',
        profile_password_mismatch: 'New password does not match.',
        profile_password_min_length: 'Password must be at least 8 characters long.',
        profile_password_current_invalid: 'Current password is invalid.',
        profile_password_change_failed: 'Failed to change password. Please try again.',
        profile_password_change_success: 'Password has been changed successfully.',
        profile_delete_success: 'Account has been deleted successfully.',
        profile_delete_failed: 'Failed to delete account',
        loading: 'Loading...',
        saving: 'Saving...',
        saved_success: 'Saved successfully.',

        // Company Overview Section
        company_overview_title_reliable: 'Reliable',
        company_overview_title_partner: 'Partner',
        company_overview_description: 'RIN Korea provides comprehensive construction solutions through its Construction Materials and Construction Machinery divisions.',
        company_overview_location_label: 'Headquarters Location',
        company_overview_location_value: 'Incheon, South Korea\nTechnopark Inju (expected completion: 2026)',
        company_overview_business_number_label: 'Business Registration Number',
        company_overview_business_number_value: '747-42-00526',
        company_overview_business_division_label: 'Business Division',
        company_overview_business_division_value: 'Construction Materials / Construction Machinery',
        company_overview_learn_more: 'Learn More',
        company_overview_contact: 'Contact Us',
    },
    zh: {
        // Navigation
        home: '首页',
        about: '关于我们',
        products: '产品介绍',
        equipment: '设备介绍',
        shop: '在线商店',
        projects: '施工案例',
        certificates: '证书',
        qna: '客户咨询',
        news: '新闻公告',
        resources: '资料库',
        contact: '联系我们',

        // User menu
        admin: '管理员',
        user: '用户',
        revenue_management: '营收管理',
        admin_danger_zone: '管理员危险区',
        profile_settings: '个人资料设置',
        login: '登录',
        logout: '退出登录',
        welcome: '欢迎！',
        admin_account: '管理员账户',

        // Hero Section
        hero_patent: '专利号 10-2312833',
        hero_trademark: '商标号 40-1678504',
        hero_title_line1: '环保阻燃材料(单组分)',
        hero_title_line2: '新型陶瓷涂料',
        hero_inquiry_btn: '产品咨询',
        hero_purchase_btn: '购买产品',
        hero_projects_btn: '查看施工案例',
        hero_admin_youtube_edit: '编辑主要YouTube视频链接',
        hero_youtube_placeholder: '输入YouTube视频地址',
        hero_embed_preview: '转换后的嵌入地址：',
        hero_save_btn: '保存',
        hero_saving: '保存中...',
        hero_save_success: 'YouTube链接已保存。',

        // Features Section
        features_title: 'RIN Korea的',
        features_title_highlight: '特色之处',
        features_subtitle: '以最高品质的陶瓷涂料创造安全环保的建筑环境',

        // Feature items
        feature_fire_resistant_title: '阻燃认证',
        feature_fire_resistant_desc: '安全的纯无机陶瓷涂料',
        feature_eco_friendly_title: '环保施工工艺',
        feature_eco_friendly_desc: '考虑环境的环保型单组分新型陶瓷涂料',
        feature_quality_title: '优秀品质',
        feature_quality_desc: '通过各种测试报告和认证，在1000多个现场应用中验证的品质',
        feature_industrial_title: '工业应用',
        feature_industrial_desc: '在各种建筑现场验证的可靠性',
        feature_time_saving_title: '缩短工期',
        feature_time_saving_desc: '大幅缩短混凝土抛光步骤，实现简便快速施工',
        feature_verified_title: '验证性能',
        feature_verified_desc: '通过严格质量测试的产品',

        // Footer
        footer_company_info: '公司信息',
        footer_address: '仁川广域市西区白凡路707号 (注安国家产业园区)',
        footer_business_number: '营业执照号码: 747-42-00526',
        footer_quick_links: '快速链接',
        footer_customer_service: '客户服务',
        footer_social_media: '社交媒体',
        footer_copyright: '© 2025 RIN Korea. 版权所有.',

        // About Page
        about_hero_title: '关于我们',
        about_hero_subtitle: 'RIN Korea是建筑材料制造专业企业，以创新技术和品质为建筑行业树立新标准。',
        about_intro_title: 'RIN Korea 介绍',
        about_intro_description: 'RIN Korea在建筑材料和建筑机械领域提供创新解决方案，已发展成为专业企业。我们将以最高的品质和技术力成为客户成功的最佳合作伙伴。',
        about_vision: '愿景',
        about_vision_desc: '引领建筑行业创新的全球企业',
        about_mission: '使命',
        about_mission_desc: '以最高品质和技术创造客户价值',
        about_core_values: '核心价值',
        about_core_values_desc: '信任、创新、可持续性',
        about_business_title: '业务领域',
        about_business_subtitle: 'RIN Korea通过建筑材料和建筑机械两大核心业务引领建筑行业发展。',
        about_materials_title: '建筑材料事业部',
        about_materials_subtitle: '核心业务领域',
        about_materials_desc: '生产混凝土表面装饰单组分陶瓷涂料(阻燃材料)、防热涂料、特殊用途涂料等最高品质产品的RIN Korea核心事业部。',
        about_equipment_title: '建筑机械事业部',
        about_equipment_subtitle: 'Shanghai JS Floor Systems 官方合作伙伴',
        about_equipment_desc: '作为Shanghai JS Floor Systems的官方合作伙伴，运营韩国官方销售代理店和服务中心。是在全球建筑现场使用的混凝土研磨机和抛光机市场的领导者。',
        about_location_title: '地址信息',
        about_address_label: '地址',
        about_phone_label: '电话',
        about_email_label: '邮箱',

        // Projects Page
        projects_hero_title: '施工案例',
        projects_hero_subtitle: '查看RIN Korea创新陶瓷涂料技术应用的各种项目案例。',
        projects_add_btn: '添加项目',
        projects_no_projects: '没有注册的项目。',
        projects_admin_add: '添加新项目',
        projects_form_title_add: '添加项目',
        projects_form_title_edit: '编辑项目',
        projects_form_name: '项目名称',
        projects_form_location: '位置',
        projects_form_description: '描述',
        projects_form_image: '图片URL',
        projects_form_features: '特征',
        projects_form_category: '类别',
        projects_form_add_feature: '输入新特征',
        projects_delete_confirm: '确定要删除此项目吗？',
        projects_delete_title: '删除项目',
        projects_saving: '保存中...',
        projects_view_detail: '查看详情',

        // Additional project translations
        projects_various_title: '各种项目',
        projects_various_desc: 'RIN Korea项目案例',
        projects_delete_error: '删除项目失败。',
        projects_delete_success: '项目已删除。',

        // Products Page
        products_hero_title: '产品介绍',
        products_hero_subtitle: '来看看RIN Korea的创新产品系列，为安全环保的建筑环境提供最高品质和效率。',
        products_add_btn: '添加产品',
        products_form_title_add: '添加产品',
        products_form_title_edit: '编辑产品',
        products_form_name: '产品名称',
        products_form_description: '描述',
        products_form_image: '图片URL',
        products_form_features: '特征',
        products_form_price: '价格',
        products_form_category: '类别',
        products_form_add_feature: '输入新特征',
        products_delete_confirm: '确定要删除此产品吗？',
        products_delete_title: '删除产品',
        products_saving: '保存中...',
        products_save_success: '产品已修改。',
        products_add_success: '产品已添加。',
        products_error_occurred: '发生错误。',
        products_view_detail: '查看详情',

        // Equipment Page
        equipment_hero_title: '建筑设备介绍',
        equipment_hero_subtitle: '以最先进的混凝土研磨技术提供最高品质和效率。',
        equipment_add_btn: '添加设备',
        equipment_partnership_title: 'Shanghai JS Floor Systems 官方合作伙伴',
        equipment_partnership_desc: '作为Shanghai JS Floor Systems的官方合作伙伴，运营韩国官方销售代理店和服务中心。是在世界级建筑现场使用的混凝土研磨机市场的领导者。',
        equipment_partnership_contact: '韩国官方销售 & 官方服务中心(AS)\n地址: 仁川\n咨询电话: 032-571-1023',
        equipment_construction_tab: '建筑设备',
        equipment_diatool_tab: '钻石工具',
        equipment_premium_title: '最新型混凝土研磨机',
        equipment_premium_subtitle: '应用最先进技术的高端研磨机产品线',
        equipment_professional_title: '混凝土研磨机',
        equipment_professional_subtitle: '专业人士专用高性能研磨机系列',
        equipment_diatool_title: '钻石工具',
        equipment_diatool_subtitle: '高品质钻石工具及配件',
        equipment_diatool_empty: '钻石工具产品正在准备中。',
        equipment_diatool_add: '添加钻石工具',
        equipment_features_label: '主要特征:',
        equipment_edit_modal_title: '编辑设备',
        equipment_add_modal_title: '添加设备',
        equipment_delete_modal_title: '删除设备',
        equipment_delete_confirm: '确定要删除此设备吗？',
        equipment_form_name: '名称',
        equipment_form_description: '描述',
        equipment_form_image: '图片URL',
        equipment_form_icon: '图标',
        equipment_form_category: '类别',
        equipment_form_features: '特征',
        equipment_form_add_feature: '输入新特征',
        equipment_saving: '保存中...',

        // Common
        loading: '加载中...',
        error: '错误',
        success: '成功',
        cancel: '取消',
        confirm: '确认',
        save: '保存',
        edit: '编辑',
        delete: '删除',
        add: '添加',
        search: '搜索',
        filter: '筛选',
        reset: '重置',
        select: '请选择',
        none: '无',

        // Language names
        korean: '한국어',
        english: 'English',
        chinese: '中文',

        // QnA Page
        qna_hero_title: '客户咨询',
        qna_hero_subtitle: '如有任何疑问，请随时联系我们。专家将快速准确地为您答复。',
        qna_search_placeholder: '输入搜索词',
        qna_filter_all: '全部',
        qna_filter_public: '公开',
        qna_filter_private: '私密',
        qna_filter_answered: '已回答',
        qna_filter_unanswered: '待回答',
        qna_ask_question: '提问',
        qna_no_questions: '没有注册的问题。',
        qna_form_title_add: '写问题',
        qna_form_title_edit: '编辑问题',
        qna_form_category: '类别',
        qna_form_title: '标题',
        qna_form_content: '内容',
        qna_form_is_private: '私密问题',
        qna_form_is_private_desc: '如果勾选，只有管理员和作者可以看到此问题。',
        qna_category_general: '一般咨询',
        qna_category_product: '产品咨询',
        qna_category_order: '订单/配送',
        qna_category_technical: '技术支持',
        qna_category_other: '其他',
        qna_status_answered: '已回答',
        qna_status_pending: '待回答',
        qna_private_question: '私密问题',
        qna_public_question: '公开问题',
        qna_delete_confirm: '确定要删除这个问题吗？',
        qna_delete_title: '删除问题',
        qna_answer_placeholder: '输入您的答案...',
        qna_submit_answer: '提交答案',
        qna_edit_answer: '编辑答案',
        qna_delete_answer: '删除答案',
        qna_answer_delete_confirm: '确定要删除这个答案吗？',

        // QnA Additional
        total_inquiries: '总咨询数',
        no_search_results: '没有搜索结果',
        try_different_search: '尝试不同的关键词或筛选器',
        leave_first_inquiry: '留下您的第一个咨询',
        login_to_inquire: '登录咨询',

        // News Page
        news_hero_title: '新闻公告',
        news_hero_subtitle: '查看RIN Korea的最新消息和重要公告。',
        news_add_btn: '添加公告',
        news_no_news: '没有注册的公告。',
        news_form_title_add: '添加公告',
        news_form_title_edit: '编辑公告',
        news_form_title: '标题',
        news_form_content: '内容',
        news_form_image: '图片URL',
        news_form_category: '类别',
        news_form_is_important: '重要公告',
        news_form_is_important_desc: '如果勾选，将置顶显示。',
        news_delete_confirm: '确定要删除这个公告吗？',
        news_delete_title: '删除公告',
        news_category_announcement: '一般公告',
        news_category_event: '活动',
        news_category_update: '更新',
        news_category_maintenance: '维护',
        news_view_detail: '查看详情',
        news_important: '重要',
        news_date_format: 'YYYY.MM.DD',
        publish_immediately: '立即发布',

        // Contact Page
        contact_hero_title: '联系我们',
        contact_hero_subtitle: '如有任何疑问，请随时联系我们。',
        contact_company_info: '公司信息',
        contact_address: '地址',
        contact_phone: '电话',
        contact_fax: '传真',
        contact_email: '邮箱',
        contact_business_hours: '营业时间',
        contact_business_hours_detail: '周一至周五 09:00 - 18:00 (周六/周日/节假日休息)',
        contact_map_title: '位置',
        contact_form_title: '联系我们',
        contact_form_name: '姓名',
        contact_form_email: '邮箱',
        contact_form_phone: '电话',
        contact_form_subject: '主题',
        contact_form_message: '消息',
        contact_form_send: '发送消息',
        contact_form_required: '必需',
        contact_send_success: '消息发送成功。',
        contact_send_error: '消息发送失败。',

        // Resources Page
        resources_hero_title: '资料库',
        resources_hero_subtitle: '查看RIN Korea的产品目录、技术资料、证书等各种资料。',
        resources_add_btn: '添加资料',
        resources_no_resources: '没有注册的资料。',
        resources_form_title_add: '添加资料',
        resources_form_title_edit: '编辑资料',
        resources_form_title: '标题',
        resources_form_description: '描述',
        resources_form_file_url: '文件URL',
        resources_form_file_type: '文件类型',
        resources_form_category: '类别',
        resources_delete_confirm: '确定要删除这个资料吗？',
        resources_delete_title: '删除资料',
        resources_category_catalog: '产品目录',
        resources_category_technical: '技术资料',
        resources_category_certificate: '证书',
        resources_category_manual: '使用说明书',
        resources_category_other: '其他',
        resources_download: '下载',
        resources_file_type_pdf: 'PDF',
        resources_file_type_doc: 'DOC',
        resources_file_type_image: '图片',
        resources_file_type_other: '其他',
        search_resources: '搜索资料...',
        all_categories: '全部类别',
        download_count: '下载次数',
        hide: '隐藏',
        show: '显示',
        grid_view: '网格',
        list_view: '列表',
        total_resources_count: '共有{{count}}个资料',
        search_results_for: "'{{term}}'搜索结果",
        no_resources_found: '没有找到资料',
        try_different_filter: '尝试更改搜索条件或查看其他类别。',
        hidden: '已隐藏',
        download_count_suffix: '次',
        downloading: '下载中...',
        processing: '处理中...',

        // Shop Page
        shop_hero_title: '在线商店',
        shop_hero_subtitle: '您可以通过在线商店订购和购买RIN Korea产品。',
        shop_add_product: '添加产品',
        shop_delete_title: '删除产品',
        shop_sort_select: '排序方式选择',
        shop_sort_newest: '最新注册优先',
        shop_sort_price_low: '最低价格优先',
        shop_sort_price_high: '最高价格优先',
        shop_grid_label: '网格',
        shop_grid_setting: '网格设置',
        shop_grid_apply: '应用',
        shop_grid_applying: '应用中...',
        shop_product_out_of_stock: '缺货',
        shop_product_buy_now: '立即购买',
        shop_deleted_success: '删除成功。',
        reviews: '评论',
        currency_won: '元',

        // Shop Additional
        shop_sort_popularity: '人气',
        shop_sort_discount: '折扣',
        shop_sort_sales: '销量',
        shop_sort_rating: '评分',

        // Product Benefits
        product_benefits_title: '产品优点',
        product_benefits_subtitle: '为什么选择RIN Korea陶瓷涂料',
        product_benefits_fire_resistant_title: '阻燃认证',
        product_benefits_fire_resistant_desc: '安全的纯无机陶瓷涂料',
        product_benefits_easy_construction_title: '简单施工',
        product_benefits_easy_construction_desc: '1成分简单施工',
        product_benefits_quality_title: '优秀品质',
        product_benefits_quality_desc: '通过严格质量管理实现的优秀品质',
        product_benefits_variety_title: '多种选择',
        product_benefits_variety_desc: '多种产品线满足各种用途和要求',

        // Equipment Success Messages
        equipment_updated_success: '设备已更新。',
        equipment_added_success: '设备已添加。',

        // Certificates Page
        certificates_hero_title: '证书',
        certificates_hero_subtitle: '查看各种证书和测试报告，以验证RIN Korea的高品质和安全性。',
        certificates_add_btn: '添加证书',
        certificates_no_certificates: '没有注册的证书。',
        certificates_patent_trademark_title: '专利和商标注册',
        certificates_patent_trademark_desc: '确认RIN Korea的技术和品牌的官方文件',
        certificates_rincoat_test_title: 'RIN-COAT测试报告',
        certificates_rincoat_test_desc: '来自授权测试机构的完整测试报告结果',
        certificates_rin_test_title: 'RIN Korea测试报告',
        certificates_rin_test_desc: '验证RIN Korea产品品质的测试报告',
        certificates_type_patent: '专利注册',
        certificates_type_patent_desc: '通过1-component陶瓷制造技术专利注册，确认技术能力',
        certificates_type_fireproof: '阻燃认证',
        certificates_type_fireproof_desc: '安全的纯无机陶瓷涂料',
        certificates_type_quality: '质量测试报告',
        certificates_type_quality_desc: '您可以从授权测试机构检查各种质量测试结果',
        certificates_form_title_add: '添加证书',
        certificates_form_title_edit: '编辑证书',
        certificates_form_name: '证书名称',
        certificates_form_description: '描述',
        certificates_form_image_url: '图片URL',
        certificates_form_category: '类别',
        certificates_form_issue_date: '发行日期',
        certificates_form_expiry_date: '到期日期',
        certificates_delete_confirm: '确定要删除这个证书吗？',
        certificates_delete_title: '删除证书',
        certificates_updated: '证书已更新。',
        certificates_added: '证书已添加。',

        // QnA Form & Item Additional
        required_fields: '请输入标题和内容。',
        submit_error: '提交咨询失败。',
        anonymous: '匿名',
        hide_content: '隐藏内容',
        show_content: '显示内容',
        private_inquiry: '这是私密咨询',

        // Revenue Management
        revenue_management_title: '营收管理',
        revenue_management_subtitle: '数据驱动的营收分析和可视化，以获得业务洞察',
        revenue_dashboard: '仪表盘',
        revenue_chart_analysis: '图表分析',
        revenue_data_input: '数据输入',
        revenue_data_manage: '数据管理',
        revenue_quick_select: '快速选择',
        revenue_period: '时期',
        revenue_export_data: '导出数据',
        revenue_monthly_trend: '每月趋势',
        revenue_data_loading_error: '数据加载错误',
        revenue_no_data: '没有营收数据',
        revenue_no_data_desc: '请在数据输入标签中添加营收信息，开始分析。',
        revenue_input_data: '输入数据',

        // Revenue Table Headers
        revenue_date: '日期',
        revenue_category: '类别',
        revenue_product_name: '产品名称',
        revenue_amount: '营收',
        revenue_quantity: '数量',
        revenue_unit_price: '单价',
        revenue_region: '地区',
        revenue_customer_type: '客户类型',
        revenue_notes: '备注',

        // ProductCard
        product_card_view_detail: '查看详情',
        product_card_show: '显示',
        product_card_hide: '隐藏',
        product_card_edit: '编辑',
        product_card_delete: '删除',

        // Profile Page
        profile_settings: '个人资料设置',
        profile_subtitle: '您可以在这里查看和编辑您的个人资料。',
        profile_name: '姓名',
        profile_email: '电子邮件',
        profile_company: '公司名称',
        profile_phone: '电话号码',
        profile_phone_error: '无效的电话格式。请使用格式：010-1234-5678',
        profile_password_change: '更改密码',
        profile_current_password: '当前密码',
        profile_new_password: '新密码',
        profile_confirm_password: '确认新密码',
        profile_password_warning: '如果您忘记了密码，将无法恢复。请将密码安全保存。',
        profile_save: '保存',
        profile_saving: '保存中...',
        profile_account_delete: '删除账户',
        profile_account_delete_warning: '一旦您删除账户，所有数据将被永久删除，无法恢复。',
        profile_account_delete_confirm_title: '确认删除账户',
        profile_account_delete_confirm_message: '您确定要删除您的账户吗？此操作无法撤销，所有数据将被永久删除。',
        profile_update_success: '个人资料已成功保存。',
        profile_update_failed: '更新个人资料失败',
        profile_password_all_required: '所有字段都必须填写。',
        profile_password_mismatch: '新密码不匹配。',
        profile_password_min_length: '密码必须至少为8个字符。',
        profile_password_current_invalid: '当前密码无效。',
        profile_password_change_failed: '更改密码失败。请重试。',
        profile_password_change_success: '密码已成功更改。',
        profile_delete_success: '账户已成功删除。',
        profile_delete_failed: '删除账户失败',
        loading: '加载中...',
        saving: '保存中...',
        saved_success: '保存成功。',

        // Company Overview Section
        company_overview_title_reliable: '可靠的',
        company_overview_title_partner: '合作伙伴',
        company_overview_description: 'RIN Korea通过建筑材料和建筑机械两大核心业务，提供全面的建筑解决方案。',
        company_overview_location_label: '总部位置',
        company_overview_location_value: '韩国仁川\n仁川技术园区Inju (预计完成时间: 2026年)\n商业注册号: 747-42-00526\n业务部门: 建筑材料 / 建筑机械',
        company_overview_business_number_label: '商业注册号',
        company_overview_business_number_value: '747-42-00526',
        company_overview_business_division_label: '业务部门',
        company_overview_business_division_value: '建筑材料 / 建筑机械',
        company_overview_learn_more: '了解更多',
        company_overview_contact: '联系我们',
    },
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        // 本地存储中获取语言设置，默认值为韩语
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'ko';
    });

    useEffect(() => {
        // 语言变化时保存到本地存储
        localStorage.setItem('language', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string, fallback?: string): string => {
        const keys = key.split('.');
        let value: unknown = translations[language];

        for (const k of keys) {
            value = (value as Record<string, unknown>)?.[k];
        }

        return (value as string) || fallback || key;
    };

    const value = {
        language,
        setLanguage,
        t,
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

// 从数据库列中获取语言特定值的助手函数
export const getLocalizedValue = (
    data: Record<string, unknown> | null | undefined,
    field: string,
    language: Language,
    fallback?: string
): string => {
    if (!data) return fallback || '';

    // 生成语言特定的列名（例如：name_ko, name_en, name_zh）
    const localizedField = `${field}_${language}`;

    // 如果存在语言特定的值，则返回，否则返回默认字段值
    return (data[localizedField] as string) || (data[field] as string) || fallback || '';
};

// 用于数组的助手函数
export const getLocalizedArray = (
    data: Record<string, unknown> | null | undefined,
    field: string,
    language: Language,
    fallback?: string[]
): string[] => {
    if (!data) return fallback || [];

    const localizedField = `${field}_${language}`;

    return (data[localizedField] as string[]) || (data[field] as string[]) || fallback || [];
}; 