// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { env } from '@/lib/env';
import type { Database } from './types';

// Supabase 클라이언트 안전한 초기화
function createSupabaseClient() {
    try {
        // 환경변수 검증
        if (!env.SUPABASE_URL || !env.SUPABASE_ANON_KEY) {
            console.warn('Supabase environment variables are missing');

            // 개발 환경에서는 더미 클라이언트 반환
            if (env.DEV) {
                return createClient(
                    'https://placeholder.supabase.co',
                    'placeholder-key',
                    {
                        auth: { persistSession: false },
                        realtime: { enabled: false },
                    }
                );
            }

            throw new Error('Supabase configuration is required in production');
        }

        return createClient<Database>(
            env.SUPABASE_URL,
            env.SUPABASE_ANON_KEY,
            {
                auth: {
                    persistSession: true,
                    storageKey: 'rin-korea-auth',
                    autoRefreshToken: true,
                    detectSessionInUrl: true
                },
                realtime: {
                    enabled: true,
                    params: {
                        eventsPerSecond: 2
                    }
                },
                global: {
                    headers: {
                        'x-my-custom-header': 'rin-korea-app'
                    }
                }
            }
        );
    } catch (error) {
        console.error('Failed to create Supabase client:', error);

        // 폴백 클라이언트 (기능 제한됨)
        return createClient(
            'https://placeholder.supabase.co',
            'placeholder-key',
            {
                auth: { persistSession: false },
                realtime: { enabled: false },
            }
        );
    }
}

export const supabase = createSupabaseClient();
